Tracker:AddLocations("locations/Donate Bugs.json")
Tracker:AddLocations("locations/Donate Fish.json")
Tracker:AddLocations("locations/Donate Sea Creatures.json")
Tracker:AddLocations("locations/Museum.json")
Tracker:AddLocations("locations/New Tent.json")
Tracker:AddLocations("locations/Nook's Cranny.json")
Tracker:AddLocations("locations/Plaza.json")
Tracker:AddLocations("locations/Resident Services Building.json")
Tracker:AddLocations("locations/Resident Services Tent.json")
Tracker:AddLocations("locations/The Beach.json")
Tracker:AddLocations("locations/The Great Indoors.json")
Tracker:AddLocations("locations/Villager Photos.json")
Tracker:AddLocations("locations/Overworld.json")
